### ISSUE TITLE
双屏幕，一个横屏一个竖屏，在主屏幕正常，副屏幕上错位

### ISSUE THREAD

**Issue by 0772boy** [cuiliang/ClickShow#10]
双屏幕，一个横屏一个竖屏，在主屏幕正常，副屏幕上错位
win10 x64，两个屏幕都是2K分辨率
作者辛苦了，希望能解决。。。

**Comment by cuiliang** [comment]
下载最新的版本 1.3.3 https://github.com/cuiliang/ClickShow/releases

**Comment by cuiliang** [comment]
先关了，如果还有问题，请再reopen
