### ISSUE TITLE
右键单击也会显示两圈波纹

### ISSUE THREAD

**Issue by YandLiu** [cuiliang/ClickShow#16]
右键单击会出现两圈间隔很短的波纹，右键原地长按也是会先出现两圈，间隔比前述的长点，不过用右键划鼠标手势没这个问题
ClickShow 1.4.0，Windows 10 x64

**Comment by cuiliang** [comment]
如果使用Quicker或其它手势类软件，这是因为这类软件会先拦截右键消息，然后如果没有触发动作再模拟一个右键消息。根据挂钩顺序，如果先触发clickshow的挂钩，就会能看到两次点击了。
