### ISSUE TITLE
提示浮标跟踪丢失

### ISSUE THREAD

**Issue by mylovesaber** [cuiliang/ClickShow#19]
我这边测试发现如果一个软件需要管理员权限的时候，也就是默认情况下屏幕中间弹窗，四周暗下来的那种，点击确定后跟踪正常，但软件一旦开启，跟踪就失效，如果我点击到别的不需要提权的软件上就能立马恢复跟踪，点回那个软件就立马失去跟踪，彩色的半透明圆圈就卡在屏幕上了

**Comment by cuiliang** [comment]
请详细看Readme哦，拷贝到windows目录里使用。
