### ISSUE TITLE
软件会导致《逍遥模拟器》菜单项目点击失效！🙄

### ISSUE THREAD

**Issue by sayaig** [cuiliang/ClickShow#20]
开启后，逍遥模拟器的所有弹出菜单项目都无法响应事件。

OS: Windows 10 
Version: 10.0.19043.1165
![GIF](https://user-images.githubusercontent.com/25012170/131255742-177c8b2d-7762-4d18-9e46-9816fe3e5662.gif)

**Comment by cuiliang** [comment]
不清楚这个问题如何解决。

**Comment by cuiliang** [comment]
已更新版本，可以试试是否解决。
