### ISSUE TITLE
点击或者拖动有些软件，波纹显示位置不对

### ISSUE THREAD

**Issue by seujingwei** [cuiliang/ClickShow#21]
如题，譬如点击百度网盘.exe时，波纹显示位置无一例外在实际点击位置的偏左上处。系统是win10，显示器是3440x1440分辨率

**Comment by cuiliang** [comment]
clickshow多少版本？win10多少版本？ 缩放比例用的多少？

**Comment by seujingwei** [comment]
1.4.0与1.3.3皆有此问题。OS版本10.0.16299，缩放比例150%

**Comment by cuiliang** [comment]
![image](https://user-images.githubusercontent.com/1972649/131353717-a1470010-699d-4f84-8c72-11ba172a5799.png)
百度网盘测试了一下没有问题。 可能windows版本太老了，建议升级到当前最新版测试。

**Comment by seujingwei** [comment]
是不是没考虑缩放布局不一定为100%，我缩放布局从150%调整至100%显示位置便正确了

**Comment by cuiliang** [comment]
是因为您的系统太老不能很好的支持DPI感知造成的。我一直都是用的4k屏150%缩放的。
