### ISSUE TITLE
失效

### ISSUE THREAD

**Issue by Navasesh** [cuiliang/ClickShow#23]
开启左特效之后会导致clover文件管理器双击左键返回上级菜单功能失效

**Comment by cuiliang** [comment]
没有使用使用过clover，也不太了解clover的工作原理。
 这个本身是一个简单的鼠标挂钩，也没有拦截鼠标消息，所以我也不清楚它为什么不行。
如果有兴趣可以用代码调试一下看看。

**Comment by cuiliang** [comment]
已更新版本，可以试试是否解决。

**Comment by Navasesh** [comment]
十分感谢 问题已修复 Quicker也已付费支持

**Comment by cuiliang** [comment]
谢谢~
