### ISSUE TITLE
1.4.0 版本在 Alt+Tab 时会出现一个到多个「点击查看器」窗口

### ISSUE THREAD

**Issue by happybrisk** [cuiliang/ClickShow#24]
如图所示

![image](https://user-images.githubusercontent.com/4309688/132222161-a0ce5ba5-e597-45b2-abf9-2c479ece5527.png)

旧版（<=1.3.3） 没有这个问题。操作系统 Win10 21H1.

不清楚这个是否会导致其他问题（比如影响其他软件的操作）

**Comment by cuiliang** [comment]
感谢你提供这个信息，我等研究一下。

**Comment by cuiliang** [comment]
已更新版本，可以试试是否解决。

**Comment by happybrisk** [comment]
更新太神速了 👍🏻
测试了下 Alt+Tab 不再出现窗口

**Comment by cuiliang** [comment]
感谢反馈
