### ISSUE TITLE
更多设置一打开就崩

### ISSUE THREAD

**Issue by Galen-87** [cuiliang/ClickShow#26]
win10,最新的1.4版本,只要点击更多设置就自动崩掉退出了,这个能解决吗?

**Comment by cuiliang** [comment]
你也没有提供更详细的报错信息，没法做进一步判断。
目前没有其他人报告类似的问题，所以这个大概是和你的环境有关系的。如果自定义是windows的外观、主题、字体，可以改回默认的再试，如果是第三方镜像安装的windows，改用官方镜像安装。

**Comment by ShunCai** [comment]
日志堆栈：

应用程序: ClickShow.exe
Framework 版本: v4.0.30319
说明: 由于未经处理的异常，进程终止。
异常信息: System.IO.FileNotFoundException
   在 System.Reflection.RuntimeAssembly._nLoad(System.Reflection.AssemblyName, System.String, System.Security.Policy.Evidence, System.Reflection.RuntimeAssembly, System.Threading.StackCrawlMark ByRef, IntPtr, Boolean, Boolean, Boolean)
   在 System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(System.Reflection.AssemblyName, System.Security.Policy.Evidence, System.Reflection.RuntimeAssembly, System.Threading.StackCrawlMark ByRef, IntPtr, Boolean, Boolean, Boolean)
   在 System.Reflection.Assembly.Load(System.Reflection.AssemblyName)
   在 System.Windows.Baml2006.Baml2006SchemaContext.ResolveAssembly(BamlAssembly)
   在 System.Windows.Baml2006.Baml2006SchemaContext.ResolveBamlTypeToType(BamlType)
   在 System.Windows.Baml2006.Baml2006SchemaContext.ResolveBamlType(BamlType, Int16)
   在 System.Windows.Baml2006.Baml2006SchemaContext.GetXamlType(Int16)
   在 System.Windows.Baml2006.Baml2006Reader.Process_ElementStart()
   在 System.Windows.Baml2006.Baml2006Reader.Process_OneBamlRecord()
   在 System.Windows.Baml2006.Baml2006Reader.Process_BamlRecords()
   在 System.Windows.Baml2006.Baml2006Reader.Read()
   在 System.Windows.Markup.WpfXamlLoader.TransformNodes(System.Xaml.XamlReader, System.Xaml.XamlObjectWriter, Boolean, Boolean, Boolean, System.Xaml.IXamlLineInfo, System.Xaml.IXamlLineInfoConsumer, MS.Internal.Xaml.Context.XamlContextStack`1<System.Windows.Markup.WpfXamlFrame>, System.Windows.Markup.IStyleConnector)
   在 System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri)

异常信息: System.Windows.Markup.XamlParseException
   在 System.Windows.Markup.XamlReader.RewrapException(System.Exception, System.Xaml.IXamlLineInfo, System.Uri)
   在 System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri)
   在 System.Windows.Markup.WpfXamlLoader.LoadBaml(System.Xaml.XamlReader, Boolean, System.Object, System.Xaml.Permissions.XamlAccessLevel, System.Uri)
   在 System.Windows.Markup.XamlReader.LoadBaml(System.IO.Stream, System.Windows.Markup.ParserContext, System.Object, Boolean)
   在 ClickShow.UI.SettingsWindow.InitializeComponent()
   在 ClickShow.UI.SettingsWindow..ctor(ClickShow.Settings.AppSetting)
   在 ClickShow.MainWindow.BtnSettings_OnClick(System.Object, System.Windows.RoutedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   在 System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   在 System.Windows.Controls.Primitives.ButtonBase.OnClick()
   在 System.Windows.Controls.Button.OnClick()
   在 System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(System.Windows.Input.MouseButtonEventArgs)
   在 System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   在 System.Windows.UIElement.ReRaiseEventAs(System.Windows.DependencyObject, System.Windows.RoutedEventArgs, System.Windows.RoutedEvent)
   在 System.Windows.UIElement.OnMouseUpThunk(System.Object, System.Windows.Input.MouseButtonEventArgs)
   在 System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   在 System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   在 System.Windows.UIElement.RaiseTrustedEvent(System.Windows.RoutedEventArgs)
   在 System.Windows.Input.InputManager.ProcessStagingArea()
   在 System.Windows.Input.InputManager.ProcessInput(System.Windows.Input.InputEventArgs)
   在 System.Windows.Input.InputProviderSite.ReportInput(System.Windows.Input.InputReport)
   在 System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr, System.Windows.Input.InputMode, Int32, System.Windows.Input.RawMouseActions, Int32, Int32, Int32)
   在 System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr, MS.Internal.Interop.WindowMessage, IntPtr, IntPtr, Boolean ByRef)
   在 System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   在 MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   在 System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   在 MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   在 MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   在 System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   在 System.Windows.Application.RunDispatcher(System.Object)
   在 System.Windows.Application.RunInternal(System.Windows.Window)
   在 ClickShow.App.Main()

**Comment by ShunCai** [comment]
知道问题了，DotNetProjects.Wpf.Extended.Toolkit.dll要在同级目录，拷贝到系统目录的时候，没有同时拷贝DotNetProjects.Wpf.Extended.Toolkit.dll。

**Comment by cuiliang** [comment]
好的。感谢反馈~
