### ISSUE TITLE
开机启动不好使

### ISSUE THREAD

**Issue by bai1996** [cuiliang/ClickShow#28]
我将ClickShow设置为管理员权限启动，勾选了开机启动，但是重启后并没有自动启动

**Comment by cuiliang** [comment]
不要设置管理员权限启动。 
直接把程序和dll复制到系统目录里使用就会自动提权了。 请参考Readme说明。

**Comment by bai1996** [comment]
我觉得此法欠妥，我看看有没有其他办法解决，

**Comment by cuiliang** [comment]
为什么会欠妥呢？ 这个是正经的提权方式的。既不会权限高到管理员，又可以在高权限窗口使用。
