### ISSUE TITLE
鼠标中键按一下是两个圈

### ISSUE THREAD

**Issue by SkyAerope** [cuiliang/ClickShow#29]
中建按下去会有一个圈，弹起来也会有一个，不知道是不是我鼠标的问题

**Comment by cuiliang** [comment]
如果用了手势软件之类使用鼠标挂钩的程序，可能会出现类似现象，它们会先拦截按下，之后再模拟一个鼠标点击。
另外如果按下超过一定时间再抬起，也会有一个小圈。

**Comment by SkyAerope** [comment]
谢了
