### ISSUE TITLE
抱歉问个题外话，请问介绍截图里的系统托盘的资源指示器（彩色数字）是啥软件？谢谢

### ISSUE THREAD

**Issue by tuchit** [cuiliang/ClickShow#34]
![image](https://user-images.githubusercontent.com/30788338/147170504-09d0f6fc-1807-46f4-8117-64692faefd46.png)

**Comment by cuiliang** [comment]
clickmonitorddc 一个用来调解显示器亮度的软件。

**Comment by tuchit** [comment]
哦，谢谢。忘了，之前用过，后来作者弃更就没用了，没注意到能显示这么多
