### ISSUE TITLE
1.4.0以上的版本无法使用

### ISSUE THREAD

**Issue by xuanwu0000** [cuiliang/ClickShow#47]
无法使用
为啥1.4.0和1.4.1进不去，打开就出现在托盘，然后鼠标一拖上去自动消失了，然后1.4.0以下的版本可以正常使用

**Comment by xuanwu0000** [comment]
确认杀软应该没问题

**Comment by cuiliang** [comment]
确认一下文件是不是拷贝全了，现在应该是多了一个dll库

**Comment by xuanwu0000** [comment]
两个文件都拷完了

**Comment by cuiliang** [comment]
不太清楚了。也可以看下windows事件查看器里有没有相关的报错信息。

**Comment by xuanwu0000** [comment]
![image](https://user-images.githubusercontent.com/111079907/184365130-6b985acc-9e70-46ab-b4df-fea1e0797e2d.png)

**Comment by xuanwu0000** [comment]
还真在这报错了，但我看不懂，有没有大佬解释一下

**Comment by cuiliang** [comment]
把配置文件删掉重启一下试试，似乎配置文件损坏了。

**Comment by xuanwu0000** [comment]
是不是dll后缀那个

**Comment by xuanwu0000** [comment]
删了，还是打不开

**Comment by cuiliang** [comment]
ClickShow.setting 文件

**Comment by xuanwu0000** [comment]
![image](https://user-images.githubusercontent.com/111079907/184368638-715675d4-8e9a-4435-b047-22d0ee68a6ab.png)

一共不就这两个文件吗

**Comment by xuanwu0000** [comment]
找到了，在d盘的文档里边

**Comment by xuanwu0000** [comment]
能用了！！！

**Comment by xuanwu0000** [comment]
感谢大佬的帮助
