### ISSUE TITLE
界面一半黑

### ISSUE THREAD

**Issue by jaredtao** [cuiliang/ClickShow#5]
![企业微信截图_20210624140231](https://user-images.githubusercontent.com/10269217/123210681-edb36d80-d4f4-11eb-9ae8-0dd00aadcde5.png)

如图。
程序一开始是正常的，运行几分钟后，再从任务栏小图标点开，就出现一半黑屏。
最小化，再重新打开，还是一半黑。
重启程序后恢复正常。

昨天下午(2021/6/23)才安装的，版本大概是1.3或者1.3.1

------------------------
我的电脑环境：
![image](https://user-images.githubusercontent.com/10269217/123210954-5ac70300-d4f5-11eb-98dc-a2f993dc79e4.png)

**Comment by jaredtao** [comment]
可能不容易复现。
我电脑上就开着vs2019 和 vs2022 preview，再就是TIM 、企业微信以及Edge浏览器，没有其它东西了。

**Comment by jaredtao** [comment]
补个显示器信息，或许有关系。
双屏，左边是主屏，分辨率是3840x2160，放大200%，右边是1920x1080的扩展屏
![企业微信截图_20210624141733](https://user-images.githubusercontent.com/10269217/123212115-f311b780-d4f6-11eb-9c44-c0f0f3fd99e8.png)

**Comment by cuiliang** [comment]
这个似乎是一个和显卡驱动有关的WPF渲染bug。

**Comment by cuiliang** [comment]
归档
