### ISSUE TITLE
如果玩CSGO的时候后台没关这个，会被VAC吗(胡思乱想ing

### ISSUE THREAD

**Issue by cyb233** [cuiliang/ClickShow#8]
如题，CSGO游戏中鼠标会不断被重置到屏幕中间

**Comment by cuiliang** [comment]
因为不玩游戏，说实话我看不懂这个case😂

**Comment by cyb233** [comment]
> 因为不玩游戏，说实话我看不懂这个case😂

就是指被游戏当做瞄准辅助类的软件2333，离线打人机试了试，晃瞎眼……

**Comment by cyb233** [comment]
(这issues其实并没有什么实际意义)
